run:
  timeout: 5m
  tests: true
linters:
  disable-all: true
  enable:
    - govet
    - typecheck
    - depguard
linters-settings:
  depguard:
    rules:
      controlplane:
        list-mode: lax
        files:
          - "closed/(audit|dataset-registry|gateway|lineage|quality)/.*\\.go"
        deny:
          - pkg: "github.com/animus-labs/animus-go/closed/internal/runtimeexec"
            desc: "control plane must not import runtime execution packages"
issues:
  exclude-dirs:
    - .cache
  max-issues-per-linter: 0
  max-same-issues: 0
