openapi: 3.0.3
info:
  title: Animus Experiments API
  version: 0.2.0
  description: |
    Experiment registry, immutable run records, and CI integrations.

    In most deployments this service is accessed through the gateway (which enforces auth/RBAC).
servers:
  - url: http://localhost:8083
paths:
  /healthz:
    get:
      summary: Liveness probe
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /readyz:
    get:
      summary: Readiness probe
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /experiments:
    get:
      summary: List experiments
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 500
          description: Max number of experiments to return.
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: Optional exact name filter.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExperimentListResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      summary: Create an experiment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateExperimentRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Experiment"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Experiment name already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /experiments/{experiment_id}:
    get:
      summary: Get experiment by ID
      parameters:
        - name: experiment_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Experiment"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /experiments/{experiment_id}/runs:
    get:
      summary: List experiment runs
      parameters:
        - name: experiment_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 500
          description: Max number of runs to return.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExperimentRunListResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      summary: Create an experiment run
      description: |
        Creates an immutable experiment run record.

        If `dataset_version_id` is provided, the run creation is blocked unless the referenced dataset version
        has a `quality_rule_id` and the latest evaluation for that rule/version is `pass`.
      parameters:
        - name: experiment_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateExperimentRunRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExperimentRun"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Quality gate failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /experiment-runs/{run_id}:
    get:
      summary: Get run by ID
      parameters:
        - name: run_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExperimentRun"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /ci/webhook:
    post:
      summary: Attach CI context to a run (signed)
      description: |
        Signed webhook for attaching CI/build metadata to an existing run.

        Signature scheme:
        - `body_sha256_hex = sha256(body_bytes)`
        - `message = ts + "\\n" + upper(method) + "\\n" + body_sha256_hex`
        - `signature = base64url(hmac_sha256(ANIMUS_CI_WEBHOOK_SECRET, message))` (no padding)
      parameters:
        - name: X-Animus-CI-Ts
          in: header
          required: true
          schema:
            type: string
          description: Unix timestamp (seconds).
        - name: X-Animus-CI-Sig
          in: header
          required: true
          schema:
            type: string
          description: base64url(HMAC-SHA256) signature (no padding).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CIWebhookRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CIWebhookResponse"
        "200":
          description: Duplicate (idempotent retry)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CIWebhookResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Signature missing or invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Run not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    HealthResponse:
      type: object
      additionalProperties: false
      required: [service, status]
      properties:
        service:
          type: string
        status:
          type: string
    ErrorResponse:
      type: object
      additionalProperties: false
      required: [error, request_id]
      properties:
        error:
          type: string
        request_id:
          type: string
    Experiment:
      type: object
      additionalProperties: false
      required: [experiment_id, name, metadata, created_at, created_by]
      properties:
        experiment_id:
          type: string
        name:
          type: string
        description:
          type: string
        metadata:
          type: object
        created_at:
          type: string
          format: date-time
        created_by:
          type: string
    ExperimentListResponse:
      type: object
      additionalProperties: false
      required: [experiments]
      properties:
        experiments:
          type: array
          items:
            $ref: "#/components/schemas/Experiment"
    CreateExperimentRequest:
      type: object
      additionalProperties: false
      required: [name]
      properties:
        name:
          type: string
        description:
          type: string
        metadata:
          type: object
    ExperimentRun:
      type: object
      additionalProperties: false
      required: [run_id, experiment_id, status, started_at, params, metrics]
      properties:
        run_id:
          type: string
        experiment_id:
          type: string
        dataset_version_id:
          type: string
        status:
          type: string
          enum: [pending, running, succeeded, failed, canceled]
        started_at:
          type: string
          format: date-time
        ended_at:
          type: string
          format: date-time
        git_repo:
          type: string
        git_commit:
          type: string
        git_ref:
          type: string
        params:
          type: object
        metrics:
          type: object
        artifacts_prefix:
          type: string
    ExperimentRunListResponse:
      type: object
      additionalProperties: false
      required: [runs]
      properties:
        runs:
          type: array
          items:
            $ref: "#/components/schemas/ExperimentRun"
    CreateExperimentRunRequest:
      type: object
      additionalProperties: false
      required: [status]
      properties:
        dataset_version_id:
          type: string
        status:
          type: string
          enum: [pending, running, succeeded, failed, canceled]
        started_at:
          type: string
          format: date-time
        ended_at:
          type: string
          format: date-time
        git_repo:
          type: string
        git_commit:
          type: string
        git_ref:
          type: string
        params:
          type: object
        metrics:
          type: object
        artifacts_prefix:
          type: string
    CIWebhookRequest:
      type: object
      additionalProperties: true
      required: [run_id]
      properties:
        run_id:
          type: string
        provider:
          type: string
    CIWebhookResponse:
      type: object
      additionalProperties: true
      required: [context_id, run_id, payload_sha256]
      properties:
        status:
          type: string
        context_id:
          type: string
        run_id:
          type: string
        provider:
          type: string
        payload_sha256:
          type: string
        received_at:
          type: string
          format: date-time
        received_by:
          type: string
        payload:
          type: object

