openapi: 3.0.3
info:
  title: Animus Audit API
  version: 0.2.0
  description: |
    Central audit event query API.

    In most deployments this service is accessed through the gateway (which enforces auth/RBAC).
servers:
  - url: http://localhost:8085
paths:
  /healthz:
    get:
      summary: Liveness probe
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /readyz:
    get:
      summary: Readiness probe
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /events:
    get:
      summary: List audit events
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 500
        - name: before_event_id
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
          description: Pagination cursor (exclusive).
        - name: actor
          in: query
          required: false
          schema:
            type: string
        - name: action
          in: query
          required: false
          schema:
            type: string
        - name: resource_type
          in: query
          required: false
          schema:
            type: string
        - name: resource_id
          in: query
          required: false
          schema:
            type: string
        - name: request_id
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuditEventListResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /events/{event_id}:
    get:
      summary: Get audit event by ID
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuditEvent"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    HealthResponse:
      type: object
      additionalProperties: false
      required: [service, status]
      properties:
        service:
          type: string
        status:
          type: string
    ErrorResponse:
      type: object
      additionalProperties: false
      required: [error, request_id]
      properties:
        error:
          type: string
        request_id:
          type: string
    AuditEvent:
      type: object
      additionalProperties: false
      required:
        [event_id, occurred_at, actor, action, resource_type, resource_id, payload, integrity_sha256]
      properties:
        event_id:
          type: integer
        occurred_at:
          type: string
          format: date-time
        actor:
          type: string
        action:
          type: string
        resource_type:
          type: string
        resource_id:
          type: string
        request_id:
          type: string
        ip:
          type: string
        user_agent:
          type: string
        payload:
          type: object
        integrity_sha256:
          type: string
    AuditEventListResponse:
      type: object
      additionalProperties: false
      required: [events]
      properties:
        events:
          type: array
          items:
            $ref: "#/components/schemas/AuditEvent"
        next_before_event_id:
          type: integer

