openapi: 3.0.3
info:
  title: Animus Dataset Registry API
  version: 0.2.0
  description: |
    Dataset registration and immutable dataset versioning.

    In most deployments this service is accessed through the gateway (which enforces auth/RBAC).
servers:
  - url: http://localhost:8081
paths:
  /healthz:
    get:
      summary: Liveness probe
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /readyz:
    get:
      summary: Readiness probe
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /datasets:
    get:
      summary: List datasets
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 500
          description: Max number of datasets to return.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetListResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      summary: Create a dataset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDatasetRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dataset"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Dataset name already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /datasets/{dataset_id}:
    get:
      summary: Get dataset by ID
      parameters:
        - name: dataset_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dataset"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /datasets/{dataset_id}/versions:
    get:
      summary: List dataset versions
      parameters:
        - name: dataset_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 500
          description: Max number of versions to return.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetVersionListResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /datasets/{dataset_id}/versions/upload:
    post:
      summary: Upload a dataset version (multipart)
      parameters:
        - name: dataset_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [file]
              properties:
                file:
                  type: string
                  format: binary
                metadata:
                  type: string
                  description: Optional JSON object encoded as a string.
                quality_rule_id:
                  type: string
                  description: Optional quality rule to associate with the new dataset version.
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetVersion"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Duplicate content for dataset
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /dataset-versions/{version_id}:
    get:
      summary: Get dataset version by ID
      parameters:
        - name: version_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetVersion"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /dataset-versions/{version_id}/download:
    get:
      summary: Download dataset version object
      parameters:
        - name: version_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Dataset bytes
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Quality gate blocked download
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    HealthResponse:
      type: object
      additionalProperties: false
      required: [service, status]
      properties:
        service:
          type: string
        status:
          type: string
    ErrorResponse:
      type: object
      additionalProperties: false
      required: [error]
      properties:
        error:
          type: string
        request_id:
          type: string
    Dataset:
      type: object
      additionalProperties: false
      required: [dataset_id, name, metadata, created_at, created_by]
      properties:
        dataset_id:
          type: string
        name:
          type: string
        description:
          type: string
        metadata:
          type: object
          additionalProperties: true
        created_at:
          type: string
          format: date-time
        created_by:
          type: string
    DatasetListResponse:
      type: object
      additionalProperties: false
      required: [datasets]
      properties:
        datasets:
          type: array
          items:
            $ref: "#/components/schemas/Dataset"
    DatasetVersion:
      type: object
      additionalProperties: false
      required: [version_id, dataset_id, ordinal, content_sha256, object_key, metadata, created_at, created_by]
      properties:
        version_id:
          type: string
        dataset_id:
          type: string
        quality_rule_id:
          type: string
        ordinal:
          type: integer
          format: int64
        content_sha256:
          type: string
        object_key:
          type: string
        size_bytes:
          type: integer
          format: int64
        metadata:
          type: object
          additionalProperties: true
        created_at:
          type: string
          format: date-time
        created_by:
          type: string
    DatasetVersionListResponse:
      type: object
      additionalProperties: false
      required: [versions]
      properties:
        versions:
          type: array
          items:
            $ref: "#/components/schemas/DatasetVersion"
    CreateDatasetRequest:
      type: object
      additionalProperties: false
      required: [name]
      properties:
        name:
          type: string
        description:
          type: string
        metadata:
          type: object
          additionalProperties: true
